[build]
beforeDevCommand = "pnpm dev"
beforeBuildCommand = "pnpm build"
devPath = "http://localhost:3000"
distDir = "../.output/public"
withGlobalTauri = false

[package]
productName = "FileSorter"
version = "0.0.1"

[tauri.allowlist]

  [tauri.allowlist.dialog]
  open = true

  [tauri.allowlist.fs]
  createDir = true
  readDir = true
  renameFile = true
  scope = ["**"]

  [tauri.allowlist.path]
  all = true

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = [ ]
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
identifier = "flapili.fr"
longDescription = ""
resources = [ ]
shortDescription = ""
targets = "all"

  [tauri.bundle.deb]
  depends = [ ]

  [tauri.bundle.macOS]
  exceptionDomain = ""
  frameworks = [ ]

  [tauri.bundle.windows]
  digestAlgorithm = "sha256"
  timestampUrl = ""

[tauri.security]

[tauri.updater]
active = false

[[tauri.windows]]
fullscreen = false
height = 200
resizable = true
title = "FileSorter"
width = 800
